### ISSUE TITLE
Returning (mapping) a `void` not so cool :P

### ISSUE THREAD

**Issue by patrickmichalina** [DiveIntoHacking/once-again-i-have-written-a-worthless-code#1]
Returning (mapping) a `void` doesn't make sense! For a side-effect it is better to use `.forEach`

```js
Array.from(document.getElementsByClassName('vb-button vb-button--appearancePrimary vb-button--small vb-mr25')).forEach((element) => element.click());
```

**Comment by gipcompany** [comment]
Hi, @patrickmichalina ! Thank you for finding the not so cool part! I noticed this issue now! I would like to have any other not cool part if you see, please give the comment! Thank you!

**Comment by gipcompany** [comment]
I fixed it. 8a1d148446ada83c7f4bc9671903713f9623c31d
